### ISSUE TITLE
Quick how-to?

### ISSUE THREAD

**Issue by MattVoda** [nobutaka/EasingCurvePresets#1]
Hi,

Thanks for making this! And preemptive newbie apologies.

I've download into a newly-made Assets/Editor folder, and see the Curve Preset Library in my project, and can open the library with the Edit button.
But I'm unclear how to apply these curves to an animation clip.

Are they intended to be called from a script? 
Could you provide a little tutorial of using one of them in an animation clip?

I am not using NGUI, just the stock Unity animations and animator controllers.

**Comment by takushima** [comment]
Hi @MattVoda 

"AnimationCurve" is low level data class. It represents an animation of single value. "AnimationClip" is more higher level component. It contains animation curves of multiple properties. They are essentially different.
Unity does not support to apply AnimationCurve data to AnimationClip through GUI.

If you wanna do it, you need to make AnimationClip instance by code.
See the first sample code in this page.
https://docs.unity3d.com/560/Documentation/ScriptReference/AnimationClip.SetCurve.html
(Need to modify the sample code slightly. Define and use public property of AnimationCurve instead of to call AnimationCurve.Linear. )
